# Generated by Django 5.2.4 on 2025-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Trio_Sub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
            ],
        ),
    ]
