# Generated by Django 5.2.4 on 2025-07-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Trio_Sub', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='collaborations/')),
            ],
        ),
    ]
