# Generated by Django 5.2.4 on 2025-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Trio_Sub', '0003_collaboration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='job_icons/')),
                ('description', models.TextField()),
            ],
        ),
    ]
