# Generated by Django 5.2.4 on 2025-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Trio_Sub', '0004_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
