# Generated by Django 4.2.23 on 2025-08-15 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_Trio_Sub', '0005_collaboration_website_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='looking_for',
            field=models.TextField(default='Not specified', help_text='A brief description of what the user is looking for.'),
        ),
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='Anonymous', help_text='The full name or username of the user.', max_length=150),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, help_text="The user's email address.", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='interest',
            field=models.CharField(default='Not specified', help_text="The user's area of interest from the dropdown.", max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='occupation',
            field=models.CharField(default='Not specified', help_text="The user's occupation.", max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone',
            field=models.CharField(default='0000000000', help_text="The user's phone number.", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='signup_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
